// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PromptHub.Infrastructure.Data;

#nullable disable

namespace PromptHub.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PromptHub.Domain.Entities.GeneratedPrompt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FinalPrompt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsSaved")
                        .HasColumnType("boolean");

                    b.Property<string>("OriginalInput")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("PromptTemplateId")
                        .HasColumnType("uuid");

                    b.Property<int>("UsedRole")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PromptTemplateId");

                    b.HasIndex("UserId");

                    b.ToTable("GeneratedPrompts");
                });

            modelBuilder.Entity("PromptHub.Domain.Entities.PromptTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DefaultRole")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<string>("MasterInstruction")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RequiredVariables")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PromptTemplates");
                });

            modelBuilder.Entity("PromptHub.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PromptHub.Domain.Entities.GeneratedPrompt", b =>
                {
                    b.HasOne("PromptHub.Domain.Entities.PromptTemplate", "PromptTemplate")
                        .WithMany("GeneratedPrompts")
                        .HasForeignKey("PromptTemplateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PromptHub.Domain.Entities.User", "User")
                        .WithMany("GeneratedPrompts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PromptTemplate");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PromptHub.Domain.Entities.PromptTemplate", b =>
                {
                    b.HasOne("PromptHub.Domain.Entities.User", "User")
                        .WithMany("Templates")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PromptHub.Domain.Entities.PromptTemplate", b =>
                {
                    b.Navigation("GeneratedPrompts");
                });

            modelBuilder.Entity("PromptHub.Domain.Entities.User", b =>
                {
                    b.Navigation("GeneratedPrompts");

                    b.Navigation("Templates");
                });
#pragma warning restore 612, 618
        }
    }
}
