using PromptHub.Domain.Enums;

namespace PromptHub.Domain.Entities;

public class GeneratedPrompt
{
    public Guid Id { get; set; } = Guid.NewGuid();
    
    // The raw, simple input from the user
    public string OriginalInput { get; set; } = string.Empty;
    
    // The final structured output generated by the AI
    public string FinalPrompt { get; set; } = string.Empty;

    public RoleType UsedRole { get; set; }
    
    public DateTime GeneratedAt { get; set; } = DateTime.UtcNow;

    public bool IsSaved { get; set; } = false;
    
    // Foreign Keys
    public Guid UserId { get; set; }
    public User? User { get; set; }

    public Guid? PromptTemplateId { get; set; }
    public PromptTemplate? PromptTemplate { get; set; }
}
